version: 0.2


phases:
  build:
    commands:
      - ./build.sh

artifacts:
  name: $(cat bin/version.txt)-$CODEBUILD_START_TIME
  files:
    - 'out/*'
    - 'bin/*'

cache:
  paths:
    - 'build/*'
